"""create table

Revision ID: 11377395532c
Revises: 
Create Date: 2023-06-18 10:52:12.832093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11377395532c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
